### PR TITLE
Customizable Transformers

### LINKED ISSUE #75: Update README to not use deprecated methods
The `SimpleMetricBatchSender` has been deprecated, and so we should update the README.

New users copying the example code will see the deprecation and may become confused.  Better to use the recommended factories like `MetricBatchSenderFactory.fromHttpImplementation(...)`

### LINKED ISSUE #89: Feature request: NewRelicReporterBuilder should expose options to set custom transformers
Currently there is no option to provide custom transformers for Dropwizard metrics because the constructor of NewRelicReporter is package-scoped and the NewRelicReporterBuilder fills the transformers in a hardcoded way.

I would like to create custom transformers to:

1. add a prefix to each metric name
2. support dynamic multi-dimensional metrics, which we created as a addon on top of available Dropwizard metrics.

### PR DESCRIPTION
**Pull request by eurythmia**
Resolves #89
Resolves #75 

Add `@FunctionalInterface`s that can be used to customize how `DropwizardMetricTransformer`s report metric names and attributes to New Relic.

Update `README.md` to document how to use the new interfaces.

Expand testing to ensure backward compatibility, and exercise the new code paths.
Rename some tests for consistency between transformer test classes.

> ## original PR description comment:
> This PR resolves #89 
> 
> To enable custom transformers add methods to the `NewRelicReporterBuilder` class. This requires a little bit of refactoring to fetch default values when no custom transformers are specified.
> 
> There are some data used to create the default transformers, so expose these for use when creating custom transformers.
> 
> Add JavaDoc to the `NewRelicReporterBuilder` class.

### CODE REVIEW

**Comment by eurythmia** [comment]
Hm; it looks like this requires a little more thought before it's ready for review. I'm going to convert this to a draft for now and will re-open it when it's ready.

**Comment by eurythmia** [comment]
PR updated and reopened as ready for review.

I've integrated this code with our metrics library and confirmed that we're able to take the names of metrics registered with a Dropwizard `MetricsRegistry` and build an `Attributes` containing the Key/Value pairs encoded in the registered Metric Name. We also strip the encoded data and report the base metric name (i.e. `out.call.rates`) to New Relic.

**Comment by kford-newrelic** [comment]
@eurythmia thanks for the updates to your PR!

To answer your other question about the timeline, it will likely take us a bit of time before we can get to this - our team is actively working on other fixes and enhancements for our agent, so it's a matter of bandwidth/availability.

**Comment by eurythmia** [comment]
> @eurythmia thanks for the updates to your PR!
> 
> To answer your other question about the timeline, it will likely take us a bit of time before we can get to this - our team is actively working on other fixes and enhancements for our agent, so it's a matter of bandwidth/availability.

Thank you for the update @kford-newrelic, looking forward to working with you to get this in as resources become available!

**Review by jasonjkeller — APPROVED** [review]
👍

**Comment by jasonjkeller** [comment]
@eurythmia Thanks for this PR! It looks good to me and worked fine in my manual testing. I'll work on getting the changes into a `0.7.0` release asap.

**Comment by eurythmia** [comment]
> @eurythmia Thanks for this PR! It looks good to me and worked fine in my manual testing. I'll work on getting the changes into a `0.7.0` release asap.

Thanks! Appreciate the effort ... I'll be looking forward to that release :)

**Comment by jasonjkeller** [comment]
@eurythmia Release is out now: https://repo1.maven.org/maven2/com/newrelic/telemetry/dropwizard-metrics-newrelic/0.7.0/

**Pull request merged**
